from the_bank import Bank, Account

bank1 = Bank()
account1 = Account('test', value=0)
account2 = Account('test2', bonsoir='ok')
account2 = Account('testt', bonsoir='ok')
account_found = Account('test3', value=1000)
bank1.add(account1)
bank1.add(account2)
# bank1.transfer('test2', 'test', 200)
bank1.fix_account('test2')
# bank1.transfer('test2', 'test', 200)
bank1.fix_account('test')
bank1.transfer('test2', 'test', 200)
bank1.add(account_found)
bank1.transfer('test3', 'test2', 200)
bank1.fix_account('test3')
bank1.transfer('test3', 'test2', 200)
bank1.transfer('test2', 'test', 200)
print(bank1)
print(bank1.fix_account(3))
